import type { EditorThemeClasses } from "lexical";

export const composerTheme: EditorThemeClasses = {
  paragraph: "composer-paragraph",
  quote: "composer-quote",
  heading: {
    h1: "composer-h1",
    h2: "composer-h2",
    h3: "composer-h3",
    h4: "composer-h4",
    h5: "composer-h5",
    h6: "composer-h6",
  },
  list: {
    ul: "composer-ul",
    ol: "composer-ol",
    listitem: "composer-li",
    nested: {
      listitem: "composer-li-nested",
    },
  },
  text: {
    bold: "composer-bold",
    italic: "composer-italic",
    underline: "composer-underline",
    strikethrough: "composer-strike",
    underlineStrikethrough: "composer-underline composer-strike",
    code: "composer-code",
  },
  code: "composer-code-block",
  codeHighlight: {
    atrule: "composer-token-attr",
    attr: "composer-token-attr",
    boolean: "composer-token-property",
    builtin: "composer-token-selector",
    cdata: "composer-token-comment",
    char: "composer-token-selector",
    class: "composer-token-function",
    "class-name": "composer-token-function",
    comment: "composer-token-comment",
    constant: "composer-token-property",
    deleted: "composer-token-property",
    doctype: "composer-token-comment",
    entity: "composer-token-operator",
    function: "composer-token-function",
    important: "composer-token-variable",
    inserted: "composer-token-selector",
    keyword: "composer-token-attr",
    namespace: "composer-token-variable",
    number: "composer-token-property",
    operator: "composer-token-operator",
    prolog: "composer-token-comment",
    property: "composer-token-property",
    punctuation: "composer-token-punctuation",
    regex: "composer-token-variable",
    selector: "composer-token-selector",
    string: "composer-token-selector",
    symbol: "composer-token-property",
    tag: "composer-token-property",
    url: "composer-token-operator",
    variable: "composer-token-variable",
  },
  link: "composer-link",
};